# **WEEK 2 — BASELINE RAG**

Goal:
Build a complete RAG pipeline by connecting the Week 1
MPNet + FAISS retriever with open-source LLMs.

LLMs:
1. Qwen3-4B-Instruct-2507
2. Gemma 3 4B IT
3. Phi-4-mini-instruct

In [1]:
from google.colab import files

uploaded = files.upload()

path = list(uploaded.keys())[0]

Saving cleaned_rag_document.txt to cleaned_rag_document.txt

# **Extract Text**

In [2]:
import re

def extract_text_from_DOC(path):
  with open(path, 'r', encoding = 'utf-8') as f:
    raw_text = f.read()
  return raw_text

text = extract_text_from_DOC(path)

In [3]:
print(text[:2000])

RAG Knowledge Base

1. Retrieval-Augmented Generation

Retrieval-Augmented Generation, commonly known as RAG, is a technique that combines information retrieval with large language model generation. Instead of relying only on information stored inside the parameters of a language model, a RAG system retrieves relevant information from an external knowledge base and provides that information as context to the language model.

A typical RAG pipeline contains several stages. First, documents are collected and divided into smaller chunks. Each chunk is converted into a numerical vector representation called an embedding. These embeddings are stored in a vector database. When a user submits a question, the question is also converted into an embedding. The system compares the query embedding with document embeddings and retrieves the most relevant chunks. The retrieved chunks are then provided to a language model, which generates the final answer.

RAG can reduce hallucinations because the language model receives external evidence. However, RAG does not guarantee that the generated answer is correct. If irrelevant or incorrect documents are retrieved, the language model may generate an incorrect answer based on the retrieved information.

The quality of a RAG system depends on several factors, including document preprocessing, chunk size, chunk overlap, embedding quality, retrieval strategy, number of retrieved documents, context construction, and language model capability.

2. Document Chunking

Document chunking is the process of dividing a large document into smaller sections that can be processed by an embedding model and retrieved independently.

A document can be divided into fixed-size chunks based on characters, words, or tokens. Another approach is semantic chunking, where text is divided according to meaningful sections or topics.

Chunk size affects retrieval performance. Very small chunks may lose important context, while very large chunks may contain unrelate

# **Creating Chunks**

In [4]:
def create_chunks(text, chunk_size = 500, overlap = 100):
  chunks = []
  start = 0
  while start < len(text):
    end = start + chunk_size
    chunks.append(text[start:end])

    start += chunk_size - overlap
  return chunks

In [5]:
chunks = create_chunks(text)

print("No of Chunks:",len(chunks))

No of Chunks: 30

# **Loading MPNet Embedding Model**

In [6]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-mpnet-base-v2')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/11.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  438MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

# **Generating Embeddings**

In [7]:
def generate_embeddings(chunks, model):
  embeddings = model.encode(chunks, convert_to_numpy = True)

  return embeddings

# **Generating FAISS Indexes**

In [8]:
!pip install faiss-cpu

Collecting faiss-cpu
  Downloading faiss_cpu-1.15.0-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.8 kB)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.2)
Downloading faiss_cpu-1.15.0-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (18.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 98.2 MB/s eta 0:00:00
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.15.0

In [9]:
import faiss
import numpy as np

def create_faiss_indexed(embeddings):
  index = faiss.IndexFlatL2(embeddings.shape[1])
  index.add(embeddings)

  return index

In [10]:
chunk_embeddings = generate_embeddings(chunks, model)
index = create_faiss_indexed(chunk_embeddings)

# **Retrieval Function**

In [11]:
def retrieval(query, chunks, index, k = 3):

  query_embedding = generate_embeddings([query], model)

  distances, indices = index.search(query_embedding, k)

  results = [chunks[i] for i in indices[0]]

  return results

# **Building Context**

In [12]:
def build_context(retrieved_chunks):
  context = '\n\n'.join(retrieved_chunks)

  return context

# **Testing the Context**

In [13]:
query = "What is Retrieval-Augmented Generation?"

retrieved_chunks = retrieval(
    query,
    chunks,
    index,
    k=3
)

context = build_context(retrieved_chunks)

print("========== RETRIEVED CONTEXT ==========")
print(context)

========== RETRIEVED CONTEXT ==========
RAG Knowledge Base

1. Retrieval-Augmented Generation

Retrieval-Augmented Generation, commonly known as RAG, is a technique that combines information retrieval with large language model generation. Instead of relying only on information stored inside the parameters of a language model, a RAG system retrieves relevant information from an external knowledge base and provides that information as context to the language model.

A typical RAG pipeline contains several stages. First, documents are co

an efficiently search large collections of embeddings. FAISS is a library designed for efficient similarity search over dense vectors.

The general retrieval process is:

Query
→ Query Embedding
→ Similarity Search
→ Ranked Documents
→ Top-K Results

5. Corrective Retrieval-Augmented Generation

Corrective Retrieval-Augmented Generation, commonly called CRAG, extends traditional RAG by evaluating the quality of retrieved information before generating the final answer.

In a basic RAG system, ret

generation process more adaptive. Instead of always retrieving the same number of documents, the system can make decisions about retrieval and reflection.

Self-RAG can improve response quality, but relying on a language model to critique its own output does not necessarily guarantee that every factual claim is independently verified.

7. GraphRAG

GraphRAG is a retrieval approach that uses graph structures to represent relationships between information.

In a graph-based knowledge representatio

# **Creating Prompt**

In [14]:
def RAG_prompt(context, query):

    prompt = f"""
        Answer the question using ONLY the information provided in the context.

        If the context does not contain enough information to answer the question,
        say that the information is not available in the provided context.

        Do not use outside knowledge.

        Context:
        {context}

        Question:
        {query}

        Answer:
        """

    return prompt

# **Upload Question Doc**

In [15]:
!pip install python-docx

Collecting python-docx
  Downloading python_docx-1.2.0-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from python-docx) (6.1.1)
Requirement already satisfied: typing_extensions>=4.9.0 in /usr/local/lib/python3.12/dist-packages (from python-docx) (4.16.0)
Downloading python_docx-1.2.0-py3-none-any.whl (252 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.0/253.0 kB 11.1 MB/s eta 0:00:00
Installing collected packages: python-docx
Successfully installed python-docx-1.2.0

In [16]:
from google.colab import files
from docx import Document

uploaded_questions = files.upload()

question_path = list(uploaded_questions.keys())[0]

doc = Document(question_path)

questions = []

for table in doc.tables:
    for row in table.rows:

        cells = [cell.text.strip() for cell in row.cells]

        if len(cells) >= 3 and cells[0].startswith("Q"):
            question_id = cells[0]
            question = cells[1].replace("\n", " ").strip()
            expected_section = cells[2].replace("\n", " ").strip()

            if question_id in [f"Q{i:02d}" for i in range(1, 31)]:
                questions.append({
                    "id": question_id,
                    "question": question,
                    "expected_section": expected_section
                })

print("Number of questions:", len(questions))

for q in questions[:5]:
    print(q)

Saving phase 1 questions.docx to phase 1 questions.docx
Number of questions: 30
{'id': 'Q01', 'question': 'What is Retrieval-Augmented Generation?', 'expected_section': 'RAG'}
{'id': 'Q02', 'question': 'How does RAG use an external knowledge base?', 'expected_section': 'RAG'}
{'id': 'Q03', 'question': 'What are the main stages of a typical RAG pipeline?', 'expected_section': 'RAG'}
{'id': 'Q04', 'question': 'Why can RAG reduce hallucinations?', 'expected_section': 'RAG'}
{'id': 'Q05', 'question': 'Does RAG guarantee that generated answers are correct?', 'expected_section': 'RAG'}

# **Creating Evaluation Function**

In [17]:
import time
import pandas as pd

In [18]:
def evaluate_llm(model, model_name, questions, chunks, index, embedding_model, k=3):

    results = []

    for count, q in enumerate(questions, start=1):

        question = q["question"]
        expected_section = q["expected_section"]

        print(f"Processing {count}/30: {q['id']}")

        # -----------------------------
        # Retrieval
        # -----------------------------

        query_embedding = generate_embeddings(
            [question],
            embedding_model
        )

        distances, indices = index.search(
            query_embedding,
            k
        )

        retrieved_chunks = [
            chunks[i]
            for i in indices[0]
        ]

        context = build_context(retrieved_chunks)

        # -----------------------------
        # Hit@K
        # -----------------------------

        hits = [
            expected_section.lower() in chunk.lower()
            for chunk in retrieved_chunks
        ]

        hit_at_1 = hits[0]

        hit_at_3 = any(hits[:3])

        # -----------------------------
        # Prompt
        # -----------------------------

        prompt = RAG_prompt(
            context,
            question
        )

        # -----------------------------
        # LLM generation
        # -----------------------------

        start_time = time.perf_counter()

        response = model.create_chat_completion(
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            max_tokens=200,
            temperature=0.2
        )

        end_time = time.perf_counter()

        generation_time = end_time - start_time

        answer = response["choices"][0]["message"]["content"]

        # -----------------------------
        # Save result
        # -----------------------------

        results.append({
            "model": model_name,
            "question_id": q["id"],
            "question": question,
            "expected_section": expected_section,

            "retrieved_chunk_ids": indices[0].tolist(),
            "distances": distances[0].tolist(),

            "hit@1": hit_at_1,
            "hit@3": hit_at_3,

            "context": context,
            "answer": answer,

            "generation_time_seconds": generation_time,

            "correct": "",
            "partially_correct": "",
            "incorrect": "",
            "unsupported": "",
            "hallucinated": ""
        })

    return pd.DataFrame(results)

# **Loaing Qwen Model**

In [19]:
# !nvidia-smi

In [20]:
!pip uninstall -y llama-cpp-python
!pip install -U llama-cpp-python \
--extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cpu

WARNING: Skipping llama-cpp-python as it is not installed.
Looking in indexes: https://pypi.org/simple, https://abetlen.github.io/llama-cpp-python/whl/cpu
Collecting llama-cpp-python
  Downloading https://github.com/abetlen/llama-cpp-python/releases/download/v0.3.34/llama_cpp_python-0.3.34-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (23.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.2/23.2 MB 51.8 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from llama-cpp-python) (4.16.0)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from llama-cpp-python) (2.0.2)
Collecting diskcache>=5.6.1 (from llama-cpp-python)
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: jinja2>=2.11.3 in /usr/local/lib/python3.12/dist-packages (from llama-cpp-python) (3.1.6)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.11.3->llama-cpp-python) (3.0.3)
Downloading diskcache-5.6.3-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 2.5 MB/s eta 0:00:00
Installing collected packages: diskcache, llama-cpp-python
Successfully installed diskcache-5.6.3 llama-cpp-python-0.3.34

In [21]:
from llama_cpp import Llama

print("llama-cpp-python imported successfully")

llama-cpp-python imported successfully

In [22]:
model_qwen = Llama.from_pretrained(
    repo_id="z8086486/Qwen3-4B-Instruct-2507-Q4_K_M-GGUF",
    filename="qwen3-4b-instruct-2507-q4_k_m.gguf",
    n_ctx=4096,
    n_gpu_layers=-1,
    verbose=True
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_validators.py:205: UserWarning: The `local_dir_use_symlinks` argument is deprecated and ignored in `hf_hub_download`. Downloading to a local directory does not use symlinks anymore.
  warnings.warn(

./qwen3-4b-instruct-2507-q4_k_m.gguf: reconstructing file:   0%|          |  0.00B / 2.50GB

./qwen3-4b-instruct-2507-q4_k_m.gguf: downloading bytes:           |  0.00B

llama_model_loader: loaded meta data with 35 key-value pairs and 398 tensors from /root/.cache/huggingface/hub/models--z8086486--Qwen3-4B-Instruct-2507-Q4_K_M-GGUF/snapshots/13e674c5b9c2dfe18755afd8a9fd85b7b4484190/./qwen3-4b-instruct-2507-q4_k_m.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = qwen3
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                     general.sampling.top_k i32              = 20
llama_model_loader: - kv   3:                     general.sampling.top_p f32              = 0.800000
llama_model_loader: - kv   4:                      general.sampling.temp f32              = 0.700000
llama_model_loader: - kv   5:                               general.name str              = Qwen3 4B Instruct 2507
llama_model_loader: - kv   6:                            general.version str              = 2507
llama_model_loader: - kv   7:                           general.finetune str              = Instruct
llama_model_loader: - kv   8:                           general.basename str              = Qwen3
llama_model_loader: - kv   9:                         general.size_label str              = 4B
llama_model_loader: - kv  10:                            general.license str              = apache-2.0
llama_model_loader: - kv  11:                       general.license.link str              = https://huggingface.co/Qwen/Qwen3-4B-...
llama_model_loader: - kv  12:                               general.tags arr[str,1]       = ["text-generation"]
llama_model_loader: - kv  13:                          qwen3.block_count u32              = 36
llama_model_loader: - kv  14:                       qwen3.context_length u32              = 262144
llama_model_loader: - kv  15:                     qwen3.embedding_length u32              = 2560
llama_model_loader: - kv  16:                  qwen3.feed_forward_length u32              = 9728
llama_model_loader: - kv  17:                 qwen3.attention.head_count u32              = 32
llama_model_loader: - kv  18:              qwen3.attention.head_count_kv u32              = 8
llama_model_loader: - kv  19:                       qwen3.rope.freq_base f32              = 5000000.000000
llama_model_loader: - kv  20:     qwen3.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  21:                 qwen3.attention.key_length u32              = 128
llama_model_loader: - kv  22:               qwen3.attention.value_length u32              = 128
llama_model_loader: - kv  23:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  24:                         tokenizer.ggml.pre str              = qwen2
llama_model_loader: - kv  25:                      tokenizer.ggml.tokens arr[str,151936]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  26:                  tokenizer.ggml.token_type arr[i32,151936]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  27:                      tokenizer.ggml.merges arr[str,151387]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  28:                tokenizer.ggml.eos_token_id u32              = 151645
llama_model_loader: - kv  29:            tokenizer.ggml.padding_token_id u32              = 151643
llama_model_loader: - kv  30:                tokenizer.ggml.bos_token_id u32              = 151643
llama_model_loader: - kv  31:               tokenizer.ggml.add_bos_token bool             = false
llama_model_loader: - kv  32:                    tokenizer.chat_template str              = {%- if tools %}\n    {{- '<|im_start|>...
llama_model_loader: - kv  33:               general.quantization_version u32              = 2
llama_model_loader: - kv  34:                          general.file_type u32              = 15
llama_model_loader: - type  f32:  145 tensors
llama_model_loader: - type q4_K:  216 tensors
llama_model_loader: - type q6_K:   37 tensors
print_info: file format = GGUF V3 (latest)
print_info: file type   = Q4_K - Medium
print_info: file size   = 2.32 GiB (4.95 BPW)
init_tokenizer: initializing tokenizer for type 2
load: 0 unused tokens
load: control token: 151660 '<|fim_middle|>' is not marked as EOG
load: control token: 151659 '<|fim_prefix|>' is not marked as EOG
load: control token: 151653 '<|vision_end|>' is not marked as EOG
load: control token: 151648 '<|box_start|>' is not marked as EOG
load: control token: 151646 '<|object_ref_start|>' is not marked as EOG
load: control token: 151649 '<|box_end|>' is not marked as EOG
load: control-looking token: 128247 '</s>' was not control-type; this is probably a bug in the model. its type will be overridden
load: control token: 151655 '<|image_pad|>' is not marked as EOG
load: control token: 151651 '<|quad_end|>' is not marked as EOG
load: control token: 151647 '<|object_ref_end|>' is not marked as EOG
load: control token: 151652 '<|vision_start|>' is not marked as EOG
load: control token: 151654 '<|vision_pad|>' is not marked as EOG
load: control token: 151656 '<|video_pad|>' is not marked as EOG
load: control token: 151644 '<|im_start|>' is not marked as EOG
load: control token: 151661 '<|fim_suffix|>' is not marked as EOG
load: control token: 151650 '<|quad_start|>' is not marked as EOG
load: printing all EOG tokens:
load:   - 128247 ('</s>')
load:   - 151643 ('<|endoftext|>')
load:   - 151645 ('<|im_end|>')
load:   - 151662 ('<|fim_pad|>')
load:   - 151663 ('<|repo_name|>')
load:   - 151664 ('<|file_sep|>')
load: special tokens cache size = 27
load: token to piece cache size = 0.9311 MB
print_info: arch                  = qwen3
print_info: vocab_only            = 0
print_info: no_alloc              = 0
print_info: n_ctx_train           = 262144
print_info: n_embd_inp            = 2560
print_info: n_embd                = 2560
print_info: n_embd_out            = 2560
print_info: n_layer               = 36
print_info: n_layer_all           = 36
print_info: n_head                = 32
print_info: n_head_kv             = 8
print_info: n_rot                 = 128
print_info: n_swa                 = 0
print_info: is_swa_any            = 0
print_info: n_embd_head_k         = 128
print_info: n_embd_head_v         = 128
print_info: n_gqa                 = 4
print_info: n_embd_k_gqa          = 1024
print_info: n_embd_v_gqa          = 1024
print_info: f_norm_eps            = 0.0e+00
print_info: f_norm_rms_eps        = 1.0e-06
print_info: f_clamp_kqv           = 0.0e+00
print_info: f_max_alibi_bias      = 0.0e+00
print_info: f_logit_scale         = 0.0e+00
print_info: f_attn_scale          = 0.0e+00
print_info: f_attn_value_scale    = 0.0000
print_info: n_ff                  = 9728
print_info: n_expert              = 0
print_info: n_expert_used         = 0
print_info: n_expert_groups       = 0
print_info: n_group_used          = 0
print_info: causal attn           = 1
print_info: pooling type          = -1
print_info: rope type             = 2
print_info: rope scaling          = linear
print_info: freq_base_train       = 5000000.0
print_info: freq_scale_train      = 1
print_info: n_ctx_orig_yarn       = 262144
print_info: rope_yarn_log_mul     = 0.0000
print_info: rope_finetuned        = unknown
print_info: model type            = 4B
print_info: model params          = 4.02 B
print_info: general.name          = Qwen3 4B Instruct 2507
print_info: vocab type            = BPE
print_info: n_vocab               = 151936
print_info: n_merges              = 151387
print_info: BOS token             = 151643 '<|endoftext|>'
print_info: EOS token             = 151645 '<|im_end|>'
print_info: EOT token             = 151645 '<|im_end|>'
print_info: PAD token             = 151643 '<|endoftext|>'
print_info: LF token              = 198 'Ċ'
print_info: FIM PRE token         = 151659 '<|fim_prefix|>'
print_info: FIM SUF token         = 151661 '<|fim_suffix|>'
print_info: FIM MID token         = 151660 '<|fim_middle|>'
print_info: FIM PAD token         = 151662 '<|fim_pad|>'
print_info: FIM REP token         = 151663 '<|repo_name|>'
print_info: FIM SEP token         = 151664 '<|file_sep|>'
print_info: EOG token             = 128247 '</s>'
print_info: EOG token             = 151643 '<|endoftext|>'
print_info: EOG token             = 151645 '<|im_end|>'
print_info: EOG token             = 151662 '<|fim_pad|>'
print_info: EOG token             = 151663 '<|repo_name|>'
print_info: EOG token             = 151664 '<|file_sep|>'
print_info: max token length      = 256
load_tensors: loading model tensors, this can take a while... (mmap = true, direct_io = false)
load_tensors: layer   0 assigned to device CPU, is_swa = 0
load_tensors: layer   1 assigned to device CPU, is_swa = 0
load_tensors: layer   2 assigned to device CPU, is_swa = 0
load_tensors: layer   3 assigned to device CPU, is_swa = 0
load_tensors: layer   4 assigned to device CPU, is_swa = 0
load_tensors: layer   5 assigned to device CPU, is_swa = 0
load_tensors: layer   6 assigned to device CPU, is_swa = 0
load_tensors: layer   7 assigned to device CPU, is_swa = 0
load_tensors: layer   8 assigned to device CPU, is_swa = 0
load_tensors: layer   9 assigned to device CPU, is_swa = 0
load_tensors: layer  10 assigned to device CPU, is_swa = 0
load_tensors: layer  11 assigned to device CPU, is_swa = 0
load_tensors: layer  12 assigned to device CPU, is_swa = 0
load_tensors: layer  13 assigned to device CPU, is_swa = 0
load_tensors: layer  14 assigned to device CPU, is_swa = 0
load_tensors: layer  15 assigned to device CPU, is_swa = 0
load_tensors: layer  16 assigned to device CPU, is_swa = 0
load_tensors: layer  17 assigned to device CPU, is_swa = 0
load_tensors: layer  18 assigned to device CPU, is_swa = 0
load_tensors: layer  19 assigned to device CPU, is_swa = 0
load_tensors: layer  20 assigned to device CPU, is_swa = 0
load_tensors: layer  21 assigned to device CPU, is_swa = 0
load_tensors: layer  22 assigned to device CPU, is_swa = 0
load_tensors: layer  23 assigned to device CPU, is_swa = 0
load_tensors: layer  24 assigned to device CPU, is_swa = 0
load_tensors: layer  25 assigned to device CPU, is_swa = 0
load_tensors: layer  26 assigned to device CPU, is_swa = 0
load_tensors: layer  27 assigned to device CPU, is_swa = 0
load_tensors: layer  28 assigned to device CPU, is_swa = 0
load_tensors: layer  29 assigned to device CPU, is_swa = 0
load_tensors: layer  30 assigned to device CPU, is_swa = 0
load_tensors: layer  31 assigned to device CPU, is_swa = 0
load_tensors: layer  32 assigned to device CPU, is_swa = 0
load_tensors: layer  33 assigned to device CPU, is_swa = 0
load_tensors: layer  34 assigned to device CPU, is_swa = 0
load_tensors: layer  35 assigned to device CPU, is_swa = 0
load_tensors: layer  36 assigned to device CPU, is_swa = 0
create_tensor: loading tensor token_embd.weight
create_tensor: loading tensor output_norm.weight
create_tensor: loading tensor blk.0.attn_norm.weight
create_tensor: loading tensor blk.0.attn_q.weight
create_tensor: loading tensor blk.0.attn_k.weight
create_tensor: loading tensor blk.0.attn_v.weight
create_tensor: loading tensor blk.0.attn_output.weight
create_tensor: loading tensor blk.0.attn_k_norm.weight
create_tensor: loading tensor blk.0.attn_q_norm.weight
create_tensor: loading tensor blk.0.ffn_norm.weight
create_tensor: loading tensor blk.0.ffn_gate.weight
create_tensor: loading tensor blk.0.ffn_down.weight
create_tensor: loading tensor blk.0.ffn_up.weight
create_tensor: loading tensor blk.1.attn_norm.weight
create_tensor: loading tensor blk.1.attn_q.weight
create_tensor: loading tensor blk.1.attn_k.weight
create_tensor: loading tensor blk.1.attn_v.weight
create_tensor: loading tensor blk.1.attn_output.weight
create_tensor: loading tensor blk.1.attn_k_norm.weight
create_tensor: loading tensor blk.1.attn_q_norm.weight
create_tensor: loading tensor blk.1.ffn_norm.weight
create_tensor: loading tensor blk.1.ffn_gate.weight
create_tensor: loading tensor blk.1.ffn_down.weight
create_tensor: loading tensor blk.1.ffn_up.weight
create_tensor: loading tensor blk.2.attn_norm.weight
create_tensor: loading tensor blk.2.attn_q.weight
create_tensor: loading tensor blk.2.attn_k.weight
create_tensor: loading tensor blk.2.attn_v.weight
create_tensor: loading tensor blk.2.attn_output.weight
create_tensor: loading tensor blk.2.attn_k_norm.weight
create_tensor: loading tensor blk.2.attn_q_norm.weight
create_tensor: loading tensor blk.2.ffn_norm.weight
create_tensor: loading tensor blk.2.ffn_gate.weight
create_tensor: loading tensor blk.2.ffn_down.weight
create_tensor: loading tensor blk.2.ffn_up.weight
create_tensor: loading tensor blk.3.attn_norm.weight
create_tensor: loading tensor blk.3.attn_q.weight
create_tensor: loading tensor blk.3.attn_k.weight
create_tensor: loading tensor blk.3.attn_v.weight
create_tensor: loading tensor blk.3.attn_output.weight
create_tensor: loading tensor blk.3.attn_k_norm.weight
create_tensor: loading tensor blk.3.attn_q_norm.weight
create_tensor: loading tensor blk.3.ffn_norm.weight
create_tensor: loading tensor blk.3.ffn_gate.weight
create_tensor: loading tensor blk.3.ffn_down.weight
create_tensor: loading tensor blk.3.ffn_up.weight
create_tensor: loading tensor blk.4.attn_norm.weight
create_tensor: loading tensor blk.4.attn_q.weight
create_tensor: loading tensor blk.4.attn_k.weight
create_tensor: loading tensor blk.4.attn_v.weight
create_tensor: loading tensor blk.4.attn_output.weight
create_tensor: loading tensor blk.4.attn_k_norm.weight
create_tensor: loading tensor blk.4.attn_q_norm.weight
create_tensor: loading tensor blk.4.ffn_norm.weight
create_tensor: loading tensor blk.4.ffn_gate.weight
create_tensor: loading tensor blk.4.ffn_down.weight
create_tensor: loading tensor blk.4.ffn_up.weight
create_tensor: loading tensor blk.5.attn_norm.weight
create_tensor: loading tensor blk.5.attn_q.weight
create_tensor: loading tensor blk.5.attn_k.weight
create_tensor: loading tensor blk.5.attn_v.weight
create_tensor: loading tensor blk.5.attn_output.weight
create_tensor: loading tensor blk.5.attn_k_norm.weight
create_tensor: loading tensor blk.5.attn_q_norm.weight
create_tensor: loading tensor blk.5.ffn_norm.weight
create_tensor: loading tensor blk.5.ffn_gate.weight
create_tensor: loading tensor blk.5.ffn_down.weight
create_tensor: loading tensor blk.5.ffn_up.weight
create_tensor: loading tensor blk.6.attn_norm.weight
create_tensor: loading tensor blk.6.attn_q.weight
create_tensor: loading tensor blk.6.attn_k.weight
create_tensor: loading tensor blk.6.attn_v.weight
create_tensor: loading tensor blk.6.attn_output.weight
create_tensor: loading tensor blk.6.attn_k_norm.weight
create_tensor: loading tensor blk.6.attn_q_norm.weight
create_tensor: loading tensor blk.6.ffn_norm.weight
create_tensor: loading tensor blk.6.ffn_gate.weight
create_tensor: loading tensor blk.6.ffn_down.weight
create_tensor: loading tensor blk.6.ffn_up.weight
create_tensor: loading tensor blk.7.attn_norm.weight
create_tensor: loading tensor blk.7.attn_q.weight
create_tensor: loading tensor blk.7.attn_k.weight
create_tensor: loading tensor blk.7.attn_v.weight
create_tensor: loading tensor blk.7.attn_output.weight
create_tensor: loading tensor blk.7.attn_k_norm.weight
create_tensor: loading tensor blk.7.attn_q_norm.weight
create_tensor: loading tensor blk.7.ffn_norm.weight
create_tensor: loading tensor blk.7.ffn_gate.weight
create_tensor: loading tensor blk.7.ffn_down.weight
create_tensor: loading tensor blk.7.ffn_up.weight
create_tensor: loading tensor blk.8.attn_norm.weight
create_tensor: loading tensor blk.8.attn_q.weight
create_tensor: loading tensor blk.8.attn_k.weight
create_tensor: loading tensor blk.8.attn_v.weight
create_tensor: loading tensor blk.8.attn_output.weight
create_tensor: loading tensor blk.8.attn_k_norm.weight
create_tensor: loading tensor blk.8.attn_q_norm.weight
create_tensor: loading tensor blk.8.ffn_norm.weight
create_tensor: loading tensor blk.8.ffn_gate.weight
create_tensor: loading tensor blk.8.ffn_down.weight
create_tensor: loading tensor blk.8.ffn_up.weight
create_tensor: loading tensor blk.9.attn_norm.weight
create_tensor: loading tensor blk.9.attn_q.weight
create_tensor: loading tensor blk.9.attn_k.weight
create_tensor: loading tensor blk.9.attn_v.weight
create_tensor: loading tensor blk.9.attn_output.weight
create_tensor: loading tensor blk.9.attn_k_norm.weight
create_tensor: loading tensor blk.9.attn_q_norm.weight
create_tensor: loading tensor blk.9.ffn_norm.weight
create_tensor: loading tensor blk.9.ffn_gate.weight
create_tensor: loading tensor blk.9.ffn_down.weight
create_tensor: loading tensor blk.9.ffn_up.weight
create_tensor: loading tensor blk.10.attn_norm.weight
create_tensor: loading tensor blk.10.attn_q.weight
create_tensor: loading tensor blk.10.attn_k.weight
create_tensor: loading tensor blk.10.attn_v.weight
create_tensor: loading tensor blk.10.attn_output.weight
create_tensor: loading tensor blk.10.attn_k_norm.weight
create_tensor: loading tensor blk.10.attn_q_norm.weight
create_tensor: loading tensor blk.10.ffn_norm.weight
create_tensor: loading tensor blk.10.ffn_gate.weight
create_tensor: loading tensor blk.10.ffn_down.weight
create_tensor: loading tensor blk.10.ffn_up.weight
create_tensor: loading tensor blk.11.attn_norm.weight
create_tensor: loading tensor blk.11.attn_q.weight
create_tensor: loading tensor blk.11.attn_k.weight
create_tensor: loading tensor blk.11.attn_v.weight
create_tensor: loading tensor blk.11.attn_output.weight
create_tensor: loading tensor blk.11.attn_k_norm.weight
create_tensor: loading tensor blk.11.attn_q_norm.weight
create_tensor: loading tensor blk.11.ffn_norm.weight
create_tensor: loading tensor blk.11.ffn_gate.weight
create_tensor: loading tensor blk.11.ffn_down.weight
create_tensor: loading tensor blk.11.ffn_up.weight
create_tensor: loading tensor blk.12.attn_norm.weight
create_tensor: loading tensor blk.12.attn_q.weight
create_tensor: loading tensor blk.12.attn_k.weight
create_tensor: loading tensor blk.12.attn_v.weight
create_tensor: loading tensor blk.12.attn_output.weight
create_tensor: loading tensor blk.12.attn_k_norm.weight
create_tensor: loading tensor blk.12.attn_q_norm.weight
create_tensor: loading tensor blk.12.ffn_norm.weight
create_tensor: loading tensor blk.12.ffn_gate.weight
create_tensor: loading tensor blk.12.ffn_down.weight
create_tensor: loading tensor blk.12.ffn_up.weight
create_tensor: loading tensor blk.13.attn_norm.weight
create_tensor: loading tensor blk.13.attn_q.weight
create_tensor: loading tensor blk.13.attn_k.weight
create_tensor: loading tensor blk.13.attn_v.weight
create_tensor: loading tensor blk.13.attn_output.weight
create_tensor: loading tensor blk.13.attn_k_norm.weight
create_tensor: loading tensor blk.13.attn_q_norm.weight
create_tensor: loading tensor blk.13.ffn_norm.weight
create_tensor: loading tensor blk.13.ffn_gate.weight
create_tensor: loading tensor blk.13.ffn_down.weight
create_tensor: loading tensor blk.13.ffn_up.weight
create_tensor: loading tensor blk.14.attn_norm.weight
create_tensor: loading tensor blk.14.attn_q.weight
create_tensor: loading tensor blk.14.attn_k.weight
create_tensor: loading tensor blk.14.attn_v.weight
create_tensor: loading tensor blk.14.attn_output.weight
create_tensor: loading tensor blk.14.attn_k_norm.weight
create_tensor: loading tensor blk.14.attn_q_norm.weight
create_tensor: loading tensor blk.14.ffn_norm.weight
create_tensor: loading tensor blk.14.ffn_gate.weight
create_tensor: loading tensor blk.14.ffn_down.weight
create_tensor: loading tensor blk.14.ffn_up.weight
create_tensor: loading tensor blk.15.attn_norm.weight
create_tensor: loading tensor blk.15.attn_q.weight
create_tensor: loading tensor blk.15.attn_k.weight
create_tensor: loading tensor blk.15.attn_v.weight
create_tensor: loading tensor blk.15.attn_output.weight

In [23]:
qwen_results = evaluate_llm(
    model=model_qwen,
    model_name="Qwen3-4B-Instruct-2507",
    questions=questions,
    chunks=chunks,
    index=index,
    embedding_model=model,
    k=3
)

Processing 1/30: Q01

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   54906.08 ms /   352 tokens (  155.98 ms per token,     6.41 tokens per second)
llama_perf_context_print:        eval time =   25426.98 ms /    61 runs   (  416.84 ms per token,     2.40 tokens per second)
llama_perf_context_print:       total time =   80383.19 ms /   413 tokens
llama_perf_context_print:    graphs reused =         60
Llama.generate: 146 prefix-match hit, remaining 220 prompt tokens to eval

Processing 2/30: Q02

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   34184.81 ms /   220 tokens (  155.39 ms per token,     6.44 tokens per second)
llama_perf_context_print:        eval time =   10908.32 ms /    27 runs   (  404.01 ms per token,     2.48 tokens per second)
llama_perf_context_print:       total time =   45113.75 ms /   247 tokens
llama_perf_context_print:    graphs reused =         26
Llama.generate: 54 prefix-match hit, remaining 311 prompt tokens to eval

Processing 3/30: Q03

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   49174.76 ms /   311 tokens (  158.12 ms per token,     6.32 tokens per second)
llama_perf_context_print:        eval time =   42963.73 ms /   108 runs   (  397.81 ms per token,     2.51 tokens per second)
llama_perf_context_print:       total time =   92227.27 ms /   419 tokens
llama_perf_context_print:    graphs reused =        107
Llama.generate: 54 prefix-match hit, remaining 303 prompt tokens to eval

Processing 4/30: Q04

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   46520.30 ms /   303 tokens (  153.53 ms per token,     6.51 tokens per second)
llama_perf_context_print:        eval time =    5306.33 ms /    14 runs   (  379.02 ms per token,     2.64 tokens per second)
llama_perf_context_print:       total time =   51838.05 ms /   317 tokens
llama_perf_context_print:    graphs reused =         13
Llama.generate: 54 prefix-match hit, remaining 322 prompt tokens to eval

Processing 5/30: Q05

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   49375.68 ms /   322 tokens (  153.34 ms per token,     6.52 tokens per second)
llama_perf_context_print:        eval time =   18450.77 ms /    46 runs   (  401.10 ms per token,     2.49 tokens per second)
llama_perf_context_print:       total time =   67862.60 ms /   368 tokens
llama_perf_context_print:    graphs reused =         45
Llama.generate: 54 prefix-match hit, remaining 327 prompt tokens to eval

Processing 6/30: Q06

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   50486.35 ms /   327 tokens (  154.39 ms per token,     6.48 tokens per second)
llama_perf_context_print:        eval time =   16886.38 ms /    40 runs   (  422.16 ms per token,     2.37 tokens per second)
llama_perf_context_print:       total time =   67405.29 ms /   367 tokens
llama_perf_context_print:    graphs reused =         39
Llama.generate: 54 prefix-match hit, remaining 290 prompt tokens to eval

Processing 7/30: Q07

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   45212.86 ms /   290 tokens (  155.91 ms per token,     6.41 tokens per second)
llama_perf_context_print:        eval time =   10401.24 ms /    26 runs   (  400.05 ms per token,     2.50 tokens per second)
llama_perf_context_print:       total time =   55634.56 ms /   316 tokens
llama_perf_context_print:    graphs reused =         25
Llama.generate: 141 prefix-match hit, remaining 210 prompt tokens to eval

Processing 8/30: Q08

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   32618.48 ms /   210 tokens (  155.33 ms per token,     6.44 tokens per second)
llama_perf_context_print:        eval time =   14678.93 ms /    36 runs   (  407.75 ms per token,     2.45 tokens per second)
llama_perf_context_print:       total time =   47325.42 ms /   246 tokens
llama_perf_context_print:    graphs reused =         35
Llama.generate: 141 prefix-match hit, remaining 206 prompt tokens to eval

Processing 9/30: Q09

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   32441.73 ms /   206 tokens (  157.48 ms per token,     6.35 tokens per second)
llama_perf_context_print:        eval time =   10038.23 ms /    25 runs   (  401.53 ms per token,     2.49 tokens per second)
llama_perf_context_print:       total time =   42499.14 ms /   231 tokens
llama_perf_context_print:    graphs reused =         24
Llama.generate: 54 prefix-match hit, remaining 292 prompt tokens to eval

Processing 10/30: Q10

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   45361.39 ms /   292 tokens (  155.35 ms per token,     6.44 tokens per second)
llama_perf_context_print:        eval time =   14183.02 ms /    35 runs   (  405.23 ms per token,     2.47 tokens per second)
llama_perf_context_print:       total time =   59571.31 ms /   327 tokens
llama_perf_context_print:    graphs reused =         34
Llama.generate: 150 prefix-match hit, remaining 201 prompt tokens to eval

Processing 11/30: Q11

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   31183.70 ms /   201 tokens (  155.14 ms per token,     6.45 tokens per second)
llama_perf_context_print:        eval time =   20042.94 ms /    50 runs   (  400.86 ms per token,     2.49 tokens per second)
llama_perf_context_print:       total time =   51266.76 ms /   251 tokens
llama_perf_context_print:    graphs reused =         49
Llama.generate: 54 prefix-match hit, remaining 296 prompt tokens to eval

Processing 12/30: Q12

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   46020.05 ms /   296 tokens (  155.47 ms per token,     6.43 tokens per second)
llama_perf_context_print:        eval time =   19088.03 ms /    46 runs   (  414.96 ms per token,     2.41 tokens per second)
llama_perf_context_print:       total time =   65145.47 ms /   342 tokens
llama_perf_context_print:    graphs reused =         45
Llama.generate: 54 prefix-match hit, remaining 298 prompt tokens to eval

Processing 13/30: Q13

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   47304.81 ms /   298 tokens (  158.74 ms per token,     6.30 tokens per second)
llama_perf_context_print:        eval time =   10456.89 ms /    26 runs   (  402.19 ms per token,     2.49 tokens per second)
llama_perf_context_print:       total time =   57782.26 ms /   324 tokens
llama_perf_context_print:    graphs reused =         25
Llama.generate: 54 prefix-match hit, remaining 308 prompt tokens to eval

Processing 14/30: Q14

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   48317.57 ms /   308 tokens (  156.88 ms per token,     6.37 tokens per second)
llama_perf_context_print:        eval time =    7963.80 ms /    21 runs   (  379.23 ms per token,     2.64 tokens per second)
llama_perf_context_print:       total time =   56297.40 ms /   329 tokens
llama_perf_context_print:    graphs reused =         20
Llama.generate: 54 prefix-match hit, remaining 317 prompt tokens to eval

Processing 15/30: Q15

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   51165.51 ms /   317 tokens (  161.41 ms per token,     6.20 tokens per second)
llama_perf_context_print:        eval time =   16781.62 ms /    42 runs   (  399.56 ms per token,     2.50 tokens per second)
llama_perf_context_print:       total time =   67978.78 ms /   359 tokens
llama_perf_context_print:    graphs reused =         41
Llama.generate: 139 prefix-match hit, remaining 219 prompt tokens to eval

Processing 16/30: Q16

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   35866.38 ms /   219 tokens (  163.77 ms per token,     6.11 tokens per second)
llama_perf_context_print:        eval time =    6692.78 ms /    16 runs   (  418.30 ms per token,     2.39 tokens per second)
llama_perf_context_print:       total time =   42572.38 ms /   235 tokens
llama_perf_context_print:    graphs reused =         15
Llama.generate: 54 prefix-match hit, remaining 299 prompt tokens to eval

Processing 17/30: Q17

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   47106.20 ms /   299 tokens (  157.55 ms per token,     6.35 tokens per second)
llama_perf_context_print:        eval time =    5230.75 ms /    12 runs   (  435.90 ms per token,     2.29 tokens per second)
llama_perf_context_print:       total time =   52347.55 ms /   311 tokens
llama_perf_context_print:    graphs reused =         11
Llama.generate: 54 prefix-match hit, remaining 239 prompt tokens to eval

Processing 18/30: Q18

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   38246.69 ms /   239 tokens (  160.03 ms per token,     6.25 tokens per second)
llama_perf_context_print:        eval time =   11534.24 ms /    29 runs   (  397.73 ms per token,     2.51 tokens per second)
llama_perf_context_print:       total time =   49804.51 ms /   268 tokens
llama_perf_context_print:    graphs reused =         28
Llama.generate: 54 prefix-match hit, remaining 306 prompt tokens to eval

Processing 19/30: Q19

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   48599.16 ms /   306 tokens (  158.82 ms per token,     6.30 tokens per second)
llama_perf_context_print:        eval time =   29862.34 ms /    74 runs   (  403.55 ms per token,     2.48 tokens per second)
llama_perf_context_print:       total time =   78521.15 ms /   380 tokens
llama_perf_context_print:    graphs reused =         73
Llama.generate: 54 prefix-match hit, remaining 321 prompt tokens to eval

Processing 20/30: Q20

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   49784.61 ms /   321 tokens (  155.09 ms per token,     6.45 tokens per second)
llama_perf_context_print:        eval time =    9997.68 ms /    25 runs   (  399.91 ms per token,     2.50 tokens per second)
llama_perf_context_print:       total time =   59802.20 ms /   346 tokens
llama_perf_context_print:    graphs reused =         24
Llama.generate: 54 prefix-match hit, remaining 319 prompt tokens to eval

Processing 21/30: Q21

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   50202.78 ms /   319 tokens (  157.38 ms per token,     6.35 tokens per second)
llama_perf_context_print:        eval time =    5756.15 ms /    15 runs   (  383.74 ms per token,     2.61 tokens per second)
llama_perf_context_print:       total time =   55971.17 ms /   334 tokens
llama_perf_context_print:    graphs reused =         14
Llama.generate: 54 prefix-match hit, remaining 326 prompt tokens to eval

Processing 22/30: Q22

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   50957.05 ms /   326 tokens (  156.31 ms per token,     6.40 tokens per second)
llama_perf_context_print:        eval time =   44739.90 ms /   111 runs   (  403.06 ms per token,     2.48 tokens per second)
llama_perf_context_print:       total time =   95787.25 ms /   437 tokens
llama_perf_context_print:    graphs reused =        110
Llama.generate: 365 prefix-match hit, remaining 21 prompt tokens to eval

Processing 23/30: Q23

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =    3227.45 ms /    21 tokens (  153.69 ms per token,     6.51 tokens per second)
llama_perf_context_print:        eval time =   25280.31 ms /    64 runs   (  395.00 ms per token,     2.53 tokens per second)
llama_perf_context_print:       total time =   28555.87 ms /    85 tokens
llama_perf_context_print:    graphs reused =         63
Llama.generate: 54 prefix-match hit, remaining 304 prompt tokens to eval

Processing 24/30: Q24

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   45119.44 ms /   304 tokens (  148.42 ms per token,     6.74 tokens per second)
llama_perf_context_print:        eval time =    6969.81 ms /    17 runs   (  409.99 ms per token,     2.44 tokens per second)
llama_perf_context_print:       total time =   52103.86 ms /   321 tokens
llama_perf_context_print:    graphs reused =         16
Llama.generate: 54 prefix-match hit, remaining 301 prompt tokens to eval

Processing 25/30: Q25

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   49145.43 ms /   301 tokens (  163.27 ms per token,     6.12 tokens per second)
llama_perf_context_print:        eval time =   15252.00 ms /    37 runs   (  412.22 ms per token,     2.43 tokens per second)
llama_perf_context_print:       total time =   64426.22 ms /   338 tokens
llama_perf_context_print:    graphs reused =         36
Llama.generate: 54 prefix-match hit, remaining 313 prompt tokens to eval

Processing 26/30: Q26

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   49309.19 ms /   313 tokens (  157.54 ms per token,     6.35 tokens per second)
llama_perf_context_print:        eval time =   45654.26 ms /   115 runs   (  396.99 ms per token,     2.52 tokens per second)
llama_perf_context_print:       total time =   95057.16 ms /   428 tokens
llama_perf_context_print:    graphs reused =        114
Llama.generate: 151 prefix-match hit, remaining 215 prompt tokens to eval

Processing 27/30: Q27

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   34239.24 ms /   215 tokens (  159.25 ms per token,     6.28 tokens per second)
llama_perf_context_print:        eval time =    9762.80 ms /    24 runs   (  406.78 ms per token,     2.46 tokens per second)
llama_perf_context_print:       total time =   44020.83 ms /   239 tokens
llama_perf_context_print:    graphs reused =         23
Llama.generate: 54 prefix-match hit, remaining 303 prompt tokens to eval

Processing 28/30: Q28

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   46307.74 ms /   303 tokens (  152.83 ms per token,     6.54 tokens per second)
llama_perf_context_print:        eval time =   42736.98 ms /   107 runs   (  399.41 ms per token,     2.50 tokens per second)
llama_perf_context_print:       total time =   89132.50 ms /   410 tokens
llama_perf_context_print:    graphs reused =        106
Llama.generate: 54 prefix-match hit, remaining 319 prompt tokens to eval

Processing 29/30: Q29

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   49516.92 ms /   319 tokens (  155.23 ms per token,     6.44 tokens per second)
llama_perf_context_print:        eval time =   23332.07 ms /    57 runs   (  409.33 ms per token,     2.44 tokens per second)
llama_perf_context_print:       total time =   72894.39 ms /   376 tokens
llama_perf_context_print:    graphs reused =         56
Llama.generate: 54 prefix-match hit, remaining 323 prompt tokens to eval

Processing 30/30: Q30

llama_perf_context_print:        load time =   54907.54 ms
llama_perf_context_print: prompt eval time =   51058.21 ms /   323 tokens (  158.07 ms per token,     6.33 tokens per second)
llama_perf_context_print:        eval time =   14032.10 ms /    35 runs   (  400.92 ms per token,     2.49 tokens per second)
llama_perf_context_print:       total time =   65117.55 ms /   358 tokens
llama_perf_context_print:    graphs reused =         34

In [24]:
qwen_results.to_csv(
    "week2_qwen_results.csv",
    index=False
)

print("Qwen results saved.")

Qwen results saved.

In [25]:
files.download("week2_qwen_results.csv")

In [26]:
print("========== QWEN RETRIEVAL ==========")

print(
    "Hit@1:",
    qwen_results["hit@1"].mean() * 100,
    "%"
)

print(
    "Hit@3:",
    qwen_results["hit@3"].mean() * 100,
    "%"
)

print(
    "Average Generation Time:",
    qwen_results["generation_time_seconds"].mean(),
    "seconds"
)

========== QWEN RETRIEVAL ==========
Hit@1: 63.33333333333333 %
Hit@3: 80.0 %
Average Generation Time: 61.82482078600001 seconds

# **Remove Qwen**

In [27]:
del model_qwen

import gc
gc.collect()


try:
    import torch
    torch.cuda.empty_cache()
except:
    pass

~llama_context:        CPU compute buffer size is 306.7520 MiB, matches expectation of 306.7520 MiB

# **Load Gemma 3**

In [28]:
model_gemma = Llama.from_pretrained(
    repo_id="GijsW/gemma-3-4b-it-Q4_K_M-GGUF",
    filename="gemma-3-4b-it-q4_k_m.gguf",
    n_ctx=4096,
    n_gpu_layers=-1,
    verbose=False
)

print("Gemma 3 loaded.")

./gemma-3-4b-it-q4_k_m.gguf: reconstructing file:   0%|          |  0.00B / 2.49GB

./gemma-3-4b-it-q4_k_m.gguf: downloading bytes:           |  0.00B

llama_kv_cache_iswa: using full-size SWA cache (ref: https://github.com/ggml-org/llama.cpp/pull/13194#issuecomment-2868343055)

Gemma 3 loaded.

In [29]:
gemma_results = evaluate_llm(
    model=model_gemma,
    model_name="Gemma-3-4B-IT",
    questions=questions,
    chunks=chunks,
    index=index,
    embedding_model=model,
    k=3
)

Processing 1/30: Q01
Processing 2/30: Q02
Processing 3/30: Q03
Processing 4/30: Q04
Processing 5/30: Q05
Processing 6/30: Q06
Processing 7/30: Q07
Processing 8/30: Q08
Processing 9/30: Q09
Processing 10/30: Q10
Processing 11/30: Q11
Processing 12/30: Q12
Processing 13/30: Q13
Processing 14/30: Q14
Processing 15/30: Q15
Processing 16/30: Q16
Processing 17/30: Q17
Processing 18/30: Q18
Processing 19/30: Q19
Processing 20/30: Q20
Processing 21/30: Q21
Processing 22/30: Q22
Processing 23/30: Q23
Processing 24/30: Q24
Processing 25/30: Q25
Processing 26/30: Q26
Processing 27/30: Q27
Processing 28/30: Q28
Processing 29/30: Q29
Processing 30/30: Q30

In [30]:
gemma_results.to_csv(
    "week2_gemma_results.csv",
    index=False
)

files.download("week2_gemma_results.csv")

# **Remove Gemma**

In [31]:
del model_gemma

import gc
gc.collect()

try:
    import torch
    torch.cuda.empty_cache()
except:
    pass

# **Load Phi-4-mini**

In [32]:
model_phi = Llama.from_pretrained(
    repo_id="Jackapan/Phi-4-mini-instruct-Q4_K_M-GGUF",
    filename="phi-4-mini-instruct-q4_k_m.gguf",
    n_ctx=4096,
    n_gpu_layers=-1,
    verbose=False
)

print("Phi-4-mini loaded.")

./phi-4-mini-instruct-q4_k_m.gguf: reconstructing file:   0%|          |  0.00B / 2.49GB

./phi-4-mini-instruct-q4_k_m.gguf: downloading bytes:           |  0.00B

Phi-4-mini loaded.

In [33]:
phi_results = evaluate_llm(
    model=model_phi,
    model_name="Phi-4-mini-instruct",
    questions=questions,
    chunks=chunks,
    index=index,
    embedding_model=model,
    k=3
)

Processing 1/30: Q01
Processing 2/30: Q02
Processing 3/30: Q03
Processing 4/30: Q04
Processing 5/30: Q05
Processing 6/30: Q06
Processing 7/30: Q07
Processing 8/30: Q08
Processing 9/30: Q09
Processing 10/30: Q10
Processing 11/30: Q11
Processing 12/30: Q12
Processing 13/30: Q13
Processing 14/30: Q14
Processing 15/30: Q15
Processing 16/30: Q16
Processing 17/30: Q17
Processing 18/30: Q18
Processing 19/30: Q19
Processing 20/30: Q20
Processing 21/30: Q21
Processing 22/30: Q22
Processing 23/30: Q23
Processing 24/30: Q24
Processing 25/30: Q25
Processing 26/30: Q26
Processing 27/30: Q27
Processing 28/30: Q28
Processing 29/30: Q29
Processing 30/30: Q30

In [ ]:
phi_results.to_csv(
    "week2_phi_results.csv",
    index=False
)

files.download("week2_phi_results.csv")

# **Remove Phi**

In [35]:
del model_phi

import gc
gc.collect()

try:
    import torch
    torch.cuda.empty_cache()
except:
    pass

# **Comparison Report**

In [36]:
all_results = pd.concat(
    [
        qwen_results,
        gemma_results,
        phi_results
    ],
    ignore_index=True
)

In [37]:
summary = all_results.groupby("model").agg(
    hit_at_1=("hit@1", "mean"),
    hit_at_3=("hit@3", "mean"),
    avg_generation_time=("generation_time_seconds", "mean")
).reset_index()

summary["hit_at_1"] *= 100
summary["hit_at_3"] *= 100

summary

                    model   hit_at_1  hit_at_3  avg_generation_time
0           Gemma-3-4B-IT  63.333333      80.0            51.259571
1     Phi-4-mini-instruct  63.333333      80.0            56.515647
2  Qwen3-4B-Instruct-2507  63.333333      80.0            61.824821

                    model   hit_at_1  hit_at_3  avg_generation_time
0           Gemma-3-4B-IT  63.333333      80.0            51.259571
1     Phi-4-mini-instruct  63.333333      80.0            56.515647
2  Qwen3-4B-Instruct-2507  63.333333      80.0            61.824821

In [38]:
summary.to_csv(
    "week2_llm_comparison.csv",
    index=False
)

files.download("week2_llm_comparison.csv")